### ISSUE TITLE
PynamoDB broken with botocore >= 1.11.0

### ISSUE THREAD

**Issue by ButtaKnife** [pynamodb/PynamoDB#529]
This change breaks Connection._make_api_call(): https://github.com/boto/botocore/commit/818d23505620f5091e5a4114020b66b5e6d7aa7b#diff-054181c44857a41f4e27bab9c8a6ba6e

In particular, https://github.com/pynamodb/PynamoDB/blob/master/pynamodb/connection/base.py#L357 is trying to access a `proxies` property which is no longer included on the botocore Endpoint class.

**Comment by anovis** [comment]
got same issue. See the stack trace below. 

```
File "/usr/local/lib/python3.6/site-packages/pynamodb/models.py", line 485, in get
    hash_key, range_key = cls._serialize_keys(hash_key, range_key)
  File "/usr/local/lib/python3.6/site-packages/pynamodb/models.py", line 1372, in _serialize_keys
    hash_key = cls._hash_key_attribute().serialize(hash_key)
  File "/usr/local/lib/python3.6/site-packages/pynamodb/models.py", line 1219, in _hash_key_attribute
    hash_keyname = cls._get_meta_data().hash_keyname
  File "/usr/local/lib/python3.6/site-packages/pynamodb/models.py", line 1262, in _get_meta_data
    cls._meta_table = MetaTable(cls._get_connection().describe_table())
  File "/usr/local/lib/python3.6/site-packages/pynamodb/connection/table.py", line 263, in describe_table
    return self.connection.describe_table(self.table_name)
  File "/usr/local/lib/python3.6/site-packages/pynamodb/connection/base.py", line 654, in describe_table
    tbl = self.get_meta_table(table_name, refresh=True)
  File "/usr/local/lib/python3.6/site-packages/pynamodb/connection/base.py", line 499, in get_meta_table
    data = self.dispatch(DESCRIBE_TABLE, operation_kwargs)
  File "/usr/local/lib/python3.6/site-packages/pynamodb/connection/base.py", line 313, in dispatch
    data = self._make_api_call(operation_name, operation_kwargs)
  File "/usr/local/lib/python3.6/site-packages/pynamodb/connection/base.py", line 357, in _make_api_call
    proxies=self.client._endpoint.proxies,
AttributeError: 'Endpoint' object has no attribute 'proxies'
```

**Comment by toshke** [comment]
gettings same error with botocore version `1.11.1`
```
/pynamodb/connection/base.py", line 357, in _make_api_call
    proxies=self.client._endpoint.proxies,
AttributeError: 'Endpoint' object has no attribute 'proxies'
```

**Comment by tjboring** [comment]
what's the status on this issue?

**Comment by kianxiongfoo** [comment]
Is there any temporary solution to force pynamodb to depend on botocore <= 1.11.0 instead?

**Comment by anovis** [comment]
You can just do ‘’’pip install botocore==1.10’’’  to revert botocore version

**Comment by slikk66** [comment]
Messing with botocore has caused some issues in our env with different packages.  I think we're going to fork this repo, merge the referenced PR and install off that instead until the real fix lands.

**Comment by bernard357** [comment]
As reported by @kianxiongfoo the workaround is to set an explicit version of botocore in requirements.txt. The most recent version that works is the last 1.10 release, so I ended up with:

```
boto3
botocore==1.10.84
```

**Comment by garrettheel** [comment]
This should be fixed in [3.3.1](https://github.com/pynamodb/PynamoDB/releases/tag/3.3.1), thanks for reporting

**Comment by jpwhite3** [comment]
This issue needs to be reopened. The problem persists with version 3.3.3 against latest version of boto3/botocore.
